language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
before_install:
- sudo add-apt-repository -y ppa:team-xbmc/ppa
- sudo apt-get update -qq
- sudo apt-cache search libsdl2
- sudo apt-get install -y libegl1-mesa-dev
- sudo apt-get install -y libgles2-mesa-dev
- sudo apt-get install -y  libsdl2-dev
- sudo apt-get install -y  libsdl2-image-dev 
- sudo apt-get install -y  libyaml-cpp-dev
- sudo apt-get install -y libboost-all-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
